Repository chicken-sloths/bangazon-cli-sprint2, pull requests merged in 2018-04, with the labels that each got.

#13 Some setup for the project
  .github/issue_template.md
  .github/pull_request_template.md
  .gitignore
  package-lock.json
  package.json
Labels: Joe, Kenzie

#19 Joe setup files
  app/activeCustomer.js
  app/controllers/activeCustC.js
  app/controllers/addCustPaymentOptC.js
  app/controllers/addProdToOrderC.js
  app/controllers/completeOrderC.js
  app/controllers/createCustC.js
  app/controllers/createProdC.js
  app/controllers/deleteProdC.js
  app/models/CustomersM.js
  app/models/OrdersM.js
  app/models/PaymentOptionsM.js
  app/models/ProductsM.js
  app/views/activeCustV.js
  app/views/addCustPaymentOptV.js
  app/views/addProdToOrderV.js
  app/views/completeOrderV.js
  app/views/createCustV.js
  app/views/createProdV.js
  app/views/deleteProdV.js
  bin/bangazon
Labels: Jordan, Kenzie

#20 DLK data generation
  .gitignore
  data/build-data.js
  data/customers.js
  data/faker/_customersFaker.js
  data/faker/_ordersFaker.js
  data/faker/_paymentOptionsFaker.js
  data/faker/_productOrdersFaker.js
  data/faker/_productTypesFaker.js
  data/faker/_productsFaker.js
  data/faker/index.js
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  data/randomInt.js
  package.json
Labels: Jordan, Mel

#21 option trees for addProductToOrder and createCustomer
  app/controllers/addProdToOrderC.js
  app/controllers/createCustC.js
  app/controllers/deleteProdC.js
  app/ui.js
  app/views/addProdToOrderV.js
  app/views/createCustV.js
  app/views/deleteProdV.js
Labels: Jordan, Mel

#23 Mb add prod ui
  app/controllers/addCustProdC.js
  app/ui.js
  app/views/addCustProdV.js
  app/views/createCustV.js
Labels: David, Kenzie

#22 Add payment options to active customer
  app/controllers/addCustPaymentOptC.js
  app/ui.js
  app/views/addCustPaymentOptV.js
Labels: Kenzie, Mel

#27 Select Active Customer Prompts
  app/controllers/activeCustC.js
  app/ui.js
  app/views/activeCustV.js
Labels: Kenzie, Mel

#26 Completes basic payment type prompt
  app/controllers/addCustPaymentOptC.js
  app/controllers/completeOrderC.js
  app/models/OrdersM.js
  app/models/PaymentOptionsM.js
  app/ui.js
  app/views/addCustPaymentOptV.js
  app/views/completeOrderV.js
Labels: Kenzie, Mel

#25 The Database creation
  data/faker/_productOrdersFaker.js
  data/faker/_productsFaker.js
  data/faker/index.js
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  db/database.js
  db/makeCustomersTable.js
  db/makeOrdersTable.js
  db/makePaymentOptionsTable.js
  db/makeProductOrdersTable.js
  db/makeProductTypesTable.js
  db/makeProductsTable.js
Labels: Jordan, Kenzie

#29 Dlk pay opts model
  app/models/PaymentOptionsM.js
  test/PaymentOptionsM.test.js
Labels: Jordan, Kenzie

#30 Customers Model and Tests
  app/models/CustomersM.js
  test/customer.test.js
Labels: David, Kenzie

#31 A few tests for completeOrderView
  app/views/completeOrderV.js
  test/completeOrderV.test.js
Labels: Jordan, Kenzie

#35 Restructuring our DB
  data/faker/_ordersFaker.js
  data/faker/_productsFaker.js
  data/faker/index.js
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  db/build-db.js
  db/database.js
  db/makeCustomersTable.js
  db/makeOrdersTable.js
  db/makePaymentOptionsTable.js
  db/makeProductOrdersTable.js
  db/makeProductTypesTable.js
  db/makeProductsTable.js
  db/sqlRunTemplate.js
  package.json
  test/PaymentOptionsM.test.js
  test/customer.test.js
Labels: Joe, Jordan, Kenzie, Mel

#33 Product_Orders testing and model
  app/models/ProductOrdersM.js
  test/ProductOrders.test.js
Labels: Joe, Kenzie

#34 Tests for orders model
  app/controllers/activeCustC.js
  app/models/OrdersM.js
  db/bangazon.sqlite-journal
  package.json
  test/ordersM.test.js
Labels: David, Mel

#36 Kb product model
  app/models/ProductsM.js
  db/bangazon.sqlite-journal
  test/productsM.test.js
Labels: Mel, feature

#37 Joe active cust c
  app/controllers/activeCustC.js
  app/models/CustomersM.js
  app/ui.js
Labels: David, Kenzie

#39 Customers Controller (and tests!)
  app/controllers/createCustC.js
  app/models/CustomersM.js
  app/models/ProductsM.js
  app/ui.js
  app/views/createCustV.js
  test/customer.test.js
  test/ordersM.test.js
Labels: Joe, Kenzie, Mel

#41 Kb delete prod ctrl
  app/controllers/deleteProdC.js
  app/models/ProductsM.js
  app/ui.js
Labels: Jordan, Mel, feature

#42 Dlk pay type ctrl
  app/controllers/completeOrderC.js
  app/models/OrdersM.js
  app/models/PaymentOptionsM.js
  app/ui.js
  app/views/completeOrderV.js
  data/json/paymentOptions.json
  test/PaymentOptionsM.test.js
  test/completeOrderC.test.js
  test/completeOrderV.test.js
Labels: Jordan, Kenzie, feature

#43 Joe add payment type ctrl
  app/controllers/addCustPaymentOptC.js
  app/ui.js
  app/views/addCustPaymentOptV.js
  data/faker/_paymentOptionsFaker.js
Labels: David, Jordan

#44 Mb add cust prod c
  app/controllers/addCustProdC.js
  app/models/ProductTypesM.js
  app/models/ProductsM.js
  app/ui.js
  app/views/addCustProdV.js
  test/ProductTypesM.test.js
  test/productsM.test.js
Labels: Kenzie

#46 Adding products to a customer order
  app/controllers/addProdToOrderC.js
  app/models/OrdersM.js
  app/models/ProductOrdersM.js
  app/ui.js
  app/views/addProdToOrderV.js
  test/ProductOrders.test.js
Labels: David, Kenzie

#45 Adding Payment_Types table to our database
  app/controllers/addCustPaymentOptC.js
  app/controllers/completeOrderC.js
  app/models/PaymentOptionsM.js
  app/models/PaymentTypesM.js
  app/models/ProductOrdersM.js
  app/views/addCustPaymentOptV.js
  app/views/completeOrderV.js
  data/build-data.js
  data/faker/_paymentOptionsFaker.js
  data/faker/_paymentTypesFaker.js
  data/faker/index.js
  data/json/customers.json
  data/json/orders.json
  data/json/paymentOptions.json
  data/json/paymentTypes.json
  data/json/productOrders.json
  data/json/productTypes.json
  data/json/products.json
  db/build-db.js
  db/makePaymentOptionsTable.js
  db/makePaymentTypesTable.js
  test/PaymentOptionsM.test.js
  test/ProductOrders.test.js
  test/completeOrderV.test.js
  test/customer.test.js
  test/ordersM.test.js
  test/paymentTypesM.test.js
  test/productsM.test.js
Labels: David, Kenzie, enhancement

#50 Kb ui reorg
  app/cli.js
  app/controllers/activeCustC.js
  app/controllers/addCustPaymentOptC.js
  app/controllers/addCustProdC.js
  app/controllers/addProdToOrderC.js
  app/controllers/completeOrderC.js
  app/controllers/createCustC.js
  app/controllers/deleteProdC.js
  app/controllers/index.js
  app/models/OrdersM.js
  app/ui.js
  app/views/completeOrderV.js
  test/completeOrderC.test.js
  test/completeOrderV.test.js
  test/customer.test.js
  test/ordersM.test.js
Labels: enhancement

#64 Kb update product
  app/models/ProductsM.js
  docs/module-productsModel.html
  package.json
  test/productsM.test.js
Labels: David, Joe, Jordan, feature

#66 Joe monday helly testing
  app/controllers/addCustPaymentOptC.js
  app/views/addCustPaymentOptV.js
Labels: Jordan, Kenzie

#68 Fixes #57: This mfing regex is dope and I hate prompt
  app/views/addCustProdV.js
Labels: Joe, Kenzie

#67 Kb cust valiation
  app/controllers/addCustPaymentOptC.js
  app/models/CustomersM.js
  app/views/createCustV.js
Labels: David, Joe, bug

#69 menu rejects invalid answers, has a 'not available yet' error
  app/ui.js
Labels: David, Joe, Jordan, enhancement

#72 Only display products with available quantity
  app/controllers/addProdToOrderC.js
  app/models/ProductsM.js
  app/views/addProdToOrderV.js
Labels: Jordan, Kenzie

#73 fixed the decimal thing for adding a payment type
  app/controllers/addCustPaymentOptC.js
  app/views/addCustPaymentOptV.js
Labels: Jordan, Kenzie, bug

#74 Fixes #63: Cleans up ui.js & does not allow user to input same payment type
  app/controllers/addCustPaymentOptC.js
  app/models/PaymentOptionsM.js
  app/ui.js
Labels: Joe, Jordan, Kenzie, Mel, enhancement, feature
